### ISSUE TITLE
System of running program unit 

### ISSUE THREAD

**Issue by andrey-berdnik** [ValentinSidorov/DeLorean_Team#6]
According to course assignment https://github.com/ValentinSidorov/DeLorean_Team/blob/4a36a28cbe21e8684cf9280e94aa0d38345a2fb4/docs/task.md

Create a function that will receive information from storing unit (https://github.com/ValentinSidorov/DeLorean_Team/issues/5) and run all program unit

**Comment by zonmen** [comment]
- [x] Write function to start new processes
- [ ] Cover it unit tests
- [ ] Cover it integration tests
